### ISSUE TITLE
if enabled, start page is not shown at all

### ISSUE THREAD

**Issue by yananet** [gkrid/dokuwiki-plugin-approve#18]
server is ubuntu 18.04 with apache2
if i open `dokuwiki2/doku.php?id=start`, the page shows nothing and php log gives following error.

`
[Thu Nov 07 18:13:07.223180 2019] [php7:error] [pid 108394] [client 150.87.23.201:47060] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /var/www/html/dokuwiki2/lib/plugins/approve/helper.php:28\nStack trace:\n#0 /var/www/html/dokuwiki2/lib/plugins/approve/helper.php(60): helper_plugin_approve->no_apr_namespace()\n#1 /var/www/html/dokuwiki2/lib/plugins/approve/action/approve.php(138): helper_plugin_approve->use_approve_here('start', NULL)\n#2 /var/www/html/dokuwiki2/inc/events.php(229): action_plugin_approve_approve->handle_viewer(Object(Doku_Event), NULL)\n#3 /var/www/html/dokuwiki2/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')\n#4 /var/www/html/dokuwiki2/inc/ActionRouter.php(80): Doku_Event->advise_before()\n#5 /var/www/html/dokuwiki2/inc/ActionRouter.php(48): dokuwiki\\ActionRouter->setupAction('show')\n#6 /var/www/html/dokuwiki2/inc/ActionRouter.php(60): dokuwiki\\ActionRouter->__construct()\n#7 /var/www/html/dokuwiki2/inc/actions.php(16): dokuwiki\\ActionRouter::getInstance(true)\n#8 /var/www/html/dokuwiki2/doku.php(120): act_dispatch()\n#9 {main}\n  th in /var/www/html/dokuwiki2/lib/plugins/approve/helper.php on line 28`

if plugin is disabled, then everything is fine.
Any workaround?

**Comment by solewniczak** [comment]
Do you have sqlite plugin installed? It is required by the plugin.

**Comment by yananet** [comment]
Thanks, I was using the old version without it, now I understood this is because of the dependency.

**Comment by solewniczak** [comment]
Yes, the new version of approve needs sqlite to provide some new features. Please install it and everything should work fine. Please also look at approves documentation since several new things was introduced since previous versions.
