### ISSUE TITLE
Read only users can't access pages with unapproved drafts

### ISSUE THREAD

**Issue by leggettc18** [gkrid/dokuwiki-plugin-approve#19]
We recently installed the plugin and have the hide_drafts_for_viewers option enabled. When our read only users accesses a page that has a draft waiting for approval, rather than getting the last draft their browser gives them an error page stating that they were redirected too many times. What could be the cause of this?

**Comment by leggettc18** [comment]
We also have it set so that you have to be logged in as one of our users to view any pages, and if the start page is one of the pages where the redirect issue occurs, the browser displays the too many redirects error before the login screen shows up.

**Comment by solewniczak** [comment]
This should be fixed now. Please let me know if it works for you.

**Comment by leggettc18** [comment]
Yes it is working now. Thanks for getting back so fast. Any idea when this version will be uploaded to the Extension manager so I know when to switch back to using that? Or do I just need to watch for a new "last updated" date on the extension page?

**Comment by solewniczak** [comment]
I will update the plugin version in dokuwiki.org today evening. After that it should be visible in Extension manager.

**Comment by leggettc18** [comment]
Wow, that's perfect! Thanks for all the work that you do! This extension is exactly what we needed for our workflow, its comforting to know that if bugs are found it has a very active developer, at least for the moment.
