### ISSUE TITLE
Error 500 after installing plugin

### ISSUE THREAD

**Issue by OevreFlataeker** [gkrid/dokuwiki-plugin-approve#20]
Hi,

as soon as I install the plugin I can no longer access my Wiki. I get "Error 500" for all pages and need to manually disable the plugin in plugins.local.php in order to use the Wiki again. Error is reproducable. Trying to locate a dokuwiki logfile where I can trace what the error is.. How do I enable dokuwiki logging?

**Comment by solewniczak** [comment]
Do you have sqlite dokuwiki plugin installed? Try to look into apache error log file. The error should be there.

**Comment by OevreFlataeker** [comment]
OK, there are only errors of that kind:

 

[Sun Jan 05 11:44:35.167981 2020] [php7:error] [pid 15572] [client 192.168.0.2:46807] PHP Fatal error:  Uncaught Error: Call to a member function query() on bool in /var/lib/dokuwiki/lib/plugins/notification/action/cron.php:49\nStack trace:\n#0 /usr/share/dokuwiki/inc/events.php(229): action_plugin_notification_cron->handle_indexer_tasks_run()\n#1 /usr/share/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event()\n#2 /usr/share/dokuwiki/lib/exe/indexer.php(39): Doku_Event->advise_after()\n#3 {main}\n  thrown in /var/lib/dokuwiki/lib/plugins/notification/action/cron.php on line 49, referer: https://server.home.bigigloo.de/dokuwiki/doku.php?id=tips_tricks&do=admin&page=extension&tab=search&q=change

[Sun Jan 05 11:45:06.958238 2020] [php7:error] [pid 15572] [client 192.168.0.2:46874] PHP Fatal error:  Uncaught Error: Call to a member function query() on bool in /var/lib/dokuwiki/lib/plugins/notification/action/cron.php:49\nStack trace:\n#0 /usr/share/dokuwiki/inc/events.php(229): action_plugin_notification_cron->handle_indexer_tasks_run()\n#1 /usr/share/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event()\n#2 /usr/share/dokuwiki/lib/exe/indexer.php(39): Doku_Event->advise_after()\n#3 {main}\n  thrown in /var/lib/dokuwiki/lib/plugins/notification/action/cron.php on line 49, referer: https://server.home.bigigloo.de/dokuwiki/doku.php?id=tips_tricks&do=admin&page=extension&tab=search&q=change

[Sun Jan 05 11:45:16.801017 2020] [php7:error] [pid 15566] [client 192.168.0.2:46873] PHP Fatal error:  Uncaught Error: Call to a member function query() on bool in /var/lib/dokuwiki/lib/plugins/approve/helper.php:28\nStack trace:\n#0 /var/lib/dokuwiki/lib/plugins/approve/helper.php(60): helper_plugin_approve->no_apr_namespace()\n#1 /var/lib/dokuwiki/lib/plugins/approve/action/approve.php(56): helper_plugin_approve->use_approve_here()\n#2 /usr/share/dokuwiki/inc/events.php(229): action_plugin_approve_approve->handle_diff_accept()\n#3 /usr/share/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event()\n#4 /usr/share/dokuwiki/inc/events.php(115): Doku_Event->advise_after()\n#5 /usr/share/dokuwiki/inc/events.php(256): Doku_Event->trigger()\n#6 /usr/share/dokuwiki/inc/template.php(83): trigger_event()\n#7 /var/lib/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()\n#8 /usr/share/dokuwiki/inc/actions.php(27): include('/var/lib/dokuwi...')\n#9 /usr/share/dokuwiki/doku.php(120): act_dispatch()\n#10 {main}\n  thrown in /var/lib/dokuwiki/lib/plugins/approve/helper.php on line 28, referer: https://server.home.bigigloo.de/dokuwiki/doku.php?id=tips_tricks&do=admin&page=extension&tab=search&q=change

[Sun Jan 05 11:45:25.663098 2020] [php7:error] [pid 15574] [client 192.168.0.2:46927] PHP Fatal error:  Uncaught Error: Call to a member function query() on bool in /var/lib/dokuwiki/lib/plugins/approve/helper.php:28\nStack trace:\n#0 /var/lib/dokuwiki/lib/plugins/approve/helper.php(60): helper_plugin_approve->no_apr_namespace()\n#1 /var/lib/dokuwiki/lib/plugins/approve/action/approve.php(56): helper_plugin_approve->use_approve_here()\n#2 /usr/share/dokuwiki/inc/events.php(229): action_plugin_approve_approve->handle_diff_accept()\n#3 /usr/share/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event()\n#4 /usr/share/dokuwiki/inc/events.php(115): Doku_Event->advise_after()\n#5 /usr/share/dokuwiki/inc/events.php(256): Doku_Event->trigger()\n#6 /usr/share/dokuwiki/inc/template.php(83): trigger_event()\n#7 /var/lib/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()\n#8 /usr/share/dokuwiki/inc/actions.php(27): include('/var/lib/dokuwi...')\n#9 /usr/share/dokuwiki/doku.php(120): act_dispatch()\n#10 {main}\n  thrown in /var/lib/dokuwiki/lib/plugins/approve/helper.php on line 28, referer: https://server.home.bigigloo.de/dokuwiki/doku.php?id=tips_tricks&do=admin&page=extension&tab=search&q=change

[Sun Jan 05 11:45:38.975775 2020] [php7:error] [pid 15570] [client 192.168.0.2:46955] PHP Fatal error:  Uncaught Error: Call to a member function query() on bool in /var/lib/dokuwiki/lib/plugins/approve/helper.php:28\nStack trace:\n#0 /var/lib/dokuwiki/lib/plugins/approve/helper.php(60): helper_plugin_approve->no_apr_namespace()\n#1 /var/lib/dokuwiki/lib/plugins/approve/action/approve.php(56): helper_plugin_approve->use_approve_here()\n#2 /usr/share/dokuwiki/inc/events.php(229): action_plugin_approve_approve->handle_diff_accept()\n#3 /usr/share/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event()\n#4 /usr/share/dokuwiki/inc/events.php(115): Doku_Event->advise_after()\n#5 /usr/share/dokuwiki/inc/events.php(256): Doku_Event->trigger()\n#6 /usr/share/dokuwiki/inc/template.php(83): trigger_event()\n#7 /var/lib/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()\n#8 /usr/share/dokuwiki/inc/actions.php(27): include('/var/lib/dokuwi...')\n#9 /usr/share/dokuwiki/doku.php(120): act_dispatch()\n#10 {main}\n  thrown in /var/lib/dokuwiki/lib/plugins/approve/helper.php on line 28, referer: https://server.home.bigigloo.de/dokuwiki/doku.php?id=tips_tricks <https://server.home.bigigloo.de/dokuwiki/doku.php?id=tips_tricks&do=admin&page=extension&tab=search&q=change> &do=admin&page=extension&tab=search&q=change

 

Do these suggest somethings amiss?

 

TBH I did not install sqlite beforehand. After I disabled the approve plugin I installed sqlite, then re-enabled approve. It threw the same error though.

Please advise how to provide more details how to pinpoint the cause of the problem.

Thank you!

**Comment by solewniczak** [comment]
Please update to the latest version of the approve plugin and check if the errors are still present.

**Comment by OevreFlataeker** [comment]
I don’t experience a crash anymore. The update seems to have fixed the problem. Thank you
