### ISSUE TITLE
Plugin is showing backslashes ("\") instead of colons (":")

### ISSUE THREAD

**Issue by brsomartins** [gkrid/dokuwiki-plugin-approve#22]
For some reason, the Approve plugin isn't working properly on my DokuWiki installation. It only works on pages located in the root namespace.

By placing the [syntax component](https://www.dokuwiki.org/plugin:approve#syntax) on a page, I could realize that backslashes (`\`) are shown instead of colons (`:`) and that hyperlinks to pages are broken.

![image](https://user-images.githubusercontent.com/8183003/76554369-8d6df900-6474-11ea-8e28-70685a5290e4.png)

With that in mind, I took a look at the code and found out that there are two replacement occurrences of `/` with `:` on that:

1. https://github.com/gkrid/dokuwiki-plugin-approve/blob/0c60a293fb92117ae4211b9e6d37af69354c10f0/admin.php#L41
2. https://github.com/gkrid/dokuwiki-plugin-approve/blob/0c60a293fb92117ae4211b9e6d37af69354c10f0/action/migration.php#L85

After replacing `/` with `\\` in my files, the plugin started working as expected.

![image](https://user-images.githubusercontent.com/8183003/76557281-0b80ce80-647a-11ea-85ac-e0ad62a6533c.png)

I'm not sure why this is happening on my installation, but I've considered important reporting the issue.

By the way, I'm running DokuWiki on a Windows 10 machine with [AMPPS](https://www.ampps.com).

**Comment by brsomartins** [comment]
I've just tested the same scenario in a CentOS 7 machine, and I couldn't reproduce the issue. It seems it only happens in Windows or AMPPS environment.

**Comment by solewniczak** [comment]
@brsomartins pleas try the recent version of the plugin. Now it should support the Windows environment.
