### ISSUE TITLE
AD accounts Issue

### ISSUE THREAD

**Issue by intervisionlord** [gkrid/dokuwiki-plugin-approve#30]
I am using AD auth.
When i try to set an approvers via settings they could see a link for approving page, but there is no link to confirm page when diff shown.

**Comment by solewniczak** [comment]
Can you check if it works in your wiki for the default authentication plugin?

**Comment by intervisionlord** [comment]
I found the reason of this issue. There is a conflict with FastWiki plugin.
Sorry for this issue.
