### ISSUE TITLE
Little hint in the documentation to understand the filter expressions ;)

### ISSUE THREAD

**Issue by ooleanderoo** [gkrid/dokuwiki-plugin-approve#40]
When reading your code I triped over the filter-expression and that it uses the preg_match function of php. 
With that in mind i now can use the filter much more precise. Maybe a hint in your documentation would be nice for others, too. 

To understand how to use it the german page [page](https://www.php-einfach.de/php-tutorial/regulaere-ausdruecke/) gave a good overview. 

Just one additional info:
Your filter is not exactly handling like discribed in the manual i found. It seems that is has problems with blanks even if framed with slashes. 
In my example i now use the dot as the wildcard character and i also get my desired funcionality.

**Comment by solewniczak** [comment]
What blanks aren't handled well? Can you provide me some example?

**Comment by ooleanderoo** [comment]
When I use:
`filter: /qds.0003/`
is shows me every page with names like `qds 0003.....` like i want
if I use:
`filter: /qds 0003/`
with a blank i just get no result.

**Comment by solewniczak** [comment]
The `filter` attribute filters the pages by their ids. The page id [cannot have space in it](https://www.dokuwiki.org/pagename). The spaces are automatically converted to underscores. Can you try: `filter: /qds_0003/`?

**Comment by ooleanderoo** [comment]
Ah sorry. that was the hint. 
I'm using the option `useheadings` so it shows me the titles of a page as name. In this case I mixed it up with the IDs.
When I use the IDs as filter there is no problem. 
My fault.
