### ISSUE TITLE
php warning in helper.php 

### ISSUE THREAD

**Issue by mtkirchner** [gkrid/dokuwiki-plugin-approve#43]
I get the php warning:
PHP Warning:  Trying to access array offset on value of type bool in /.../htdocs/igfwiki/lib/plugins/approve/helper.php on line 51

code is 

```
        $res = $sqlite->query('SELECT page, approver FROM page WHERE page=? AND hidden=0', $id);
        $row = $sqlite->res2row($res);
51:     $approver = $row['approver'];
        if ($row) {
            return true;
        }
        return false;

```
So I guess that line 51 should be put into the brackets as it is only valid if $row is not false.

**Comment by solewniczak** [comment]
fixed in c0f5b8e8955d46b6eceab9ac7ccb930421713568
