### ISSUE TITLE
Unable to approve pages edited externally

### ISSUE THREAD

**Issue by macin** [gkrid/dokuwiki-plugin-approve#48]
Hi, 
From time to time, we run cleanup script for our pages. These are marked as external edit as we do them directly on the file system. Unfortunatelly, those changes are not possible to be approved with the plugin. Is it possible to make the plugin to work with external edit? Thanks!

**Comment by solewniczak** [comment]
I've implemented it in last version of plugin (**2024-07-06**). Please try it out. Additionally, I've added a feature that rebuilds the pages index every time you modify "Approval Assignments". So in case of external edit just change something in Assignments and the plugin should work as usual.
